version: '3.7'

services:
  buying-system:
    build:
      context: ./buying-system
      dockerfile: Dockerfile
    image: nobueitou/buying-system:latest
    ports:
      - "8001:8000"
  
  comment-system:
    build:
      context: ./comment-system
      dockerfile: Dockerfile
    image: nobueitou/comment-system:latest
    ports:
      - "8002:8000"
  
  login-system:
    build:
      context: ./login-system
      dockerfile: Dockerfile
    image: nobueitou/login-system:latest
    ports:
      - "8003:8000"
  
  mangas:
    build:
      context: ./mangas
      dockerfile: Dockerfile
    image: nobueitou/mangas:latest
    ports:
      - "8004:8000"
  
  user-pfp:
    build:
      context: ./user-pfp
      dockerfile: Dockerfile
    image: nobueitou/user-pfp:latest
    ports:
      - "8005:8000"
  
  user-system:
    build:
      context: ./user-system
      dockerfile: Dockerfile
    image: nobueitou/user-system:latest
    ports:
      - "8006:8000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
    depends_on:
      - buying-system
      - comment-system
      - login-system
      - mangas
      - user-pfp
      - user-system
